# Generated by Django 5.2.11 on 2026-02-09 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ouid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('max_division', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['nickname'], name='users_nicknam_172a64_idx')],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('match_date', models.DateTimeField()),
                ('match_type', models.IntegerField()),
                ('result', models.CharField(choices=[('win', 'Win'), ('lose', 'Lose'), ('draw', 'Draw')], max_length=10)),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('possession', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('shots_on_target', models.IntegerField()),
                ('pass_success_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('raw_data', models.JSONField()),
                ('ouid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.user')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-match_date'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('all_time', 'All Time')], max_length=20)),
                ('total_matches', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('avg_possession', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_shots', models.DecimalField(decimal_places=2, max_digits=5)),
                ('avg_goals', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shot_accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('xg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ouid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.user')),
            ],
            options={
                'db_table': 'user_stats',
            },
        ),
        migrations.CreateModel(
            name='ShotDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=4, max_digits=5)),
                ('y', models.DecimalField(decimal_places=4, max_digits=5)),
                ('result', models.CharField(choices=[('goal', 'Goal'), ('on_target', 'On Target'), ('off_target', 'Off Target'), ('blocked', 'Blocked')], max_length=20)),
                ('shot_type', models.IntegerField()),
                ('assist_x', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('assist_y', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_details', to='api.match')),
            ],
            options={
                'db_table': 'shot_details',
                'indexes': [models.Index(fields=['match', 'result'], name='shot_detail_match_i_93c7fe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['ouid', '-match_date'], name='matches_ouid_id_f1271b_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_type'], name='matches_match_t_0c6248_idx'),
        ),
        migrations.AddIndex(
            model_name='userstats',
            index=models.Index(fields=['ouid', 'period'], name='user_stats_ouid_id_527fea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userstats',
            unique_together={('ouid', 'period')},
        ),
    ]
