# Generated by Django 5.2.11 on 2026-02-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='opponent_nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
