# Generated by Django 5.2.11 on 2026-02-10 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match_opponent_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spid', models.BigIntegerField()),
                ('player_name', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('shots', models.IntegerField(default=0)),
                ('shots_on_target', models.IntegerField(default=0)),
                ('pass_attempts', models.IntegerField(default=0)),
                ('pass_success', models.IntegerField(default=0)),
                ('dribble_attempts', models.IntegerField(default=0)),
                ('dribble_success', models.IntegerField(default=0)),
                ('tackles', models.IntegerField(default=0)),
                ('intercepts', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('aerial_attempts', models.IntegerField(default=0)),
                ('aerial_success', models.IntegerField(default=0)),
                ('pass_success_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('shot_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dribble_success_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_performances', to='api.match')),
            ],
            options={
                'db_table': 'player_performances',
                'indexes': [models.Index(fields=['match', '-rating'], name='player_perf_match_i_982bb1_idx'), models.Index(fields=['spid'], name='player_perf_spid_edb5b5_idx')],
            },
        ),
    ]
