# Generated by Django 5.2.11 on 2026-02-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_playerperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotdetail',
            name='goal_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='shotdetail',
            index=models.Index(fields=['match', 'goal_time'], name='shot_detail_match_i_07fca1_idx'),
        ),
    ]
