# Generated by Django 5.2.11 on 2026-02-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_shotdetail_goal_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='season_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
