# Generated by Django 5.2.11 on 2026-02-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_playerperformance_season_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='season_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
