# Generated by Django 5.2.11 on 2026-02-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_playerperformance_season_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerperformance',
            name='aerial_attempts',
        ),
        migrations.RemoveField(
            model_name='playerperformance',
            name='intercepts',
        ),
        migrations.RemoveField(
            model_name='playerperformance',
            name='tackles',
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='block_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='cross_success',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='crosses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='dribble_stops',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='errors_leading_to_goal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='forward_passes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='fouls',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='goals_conceded',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='interceptions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='key_passes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='long_pass_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='long_pass_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='long_pass_success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='opponent_shots',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='saves',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='short_pass_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='short_pass_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='short_pass_success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='shots_off_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='shots_woodwork',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='tackle_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='tackle_success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='tackle_success_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='through_pass_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='through_pass_success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='xg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='playerperformance',
            name='xg_against',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
