# Generated by Django 5.2.11 on 2026-02-14 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_playerperformance_aerial_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerperformance',
            name='user_ouid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_performances', to='api.user'),
        ),
    ]
