# Generated by Django 5.2.11 on 2026-02-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_playerperformance_user_ouid'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # Drop dependent foreign keys
                "ALTER TABLE shot_details DROP CONSTRAINT IF EXISTS shot_details_match_id_4b0af562_fk_matches_match_id CASCADE;",
                "ALTER TABLE player_performances DROP CONSTRAINT IF EXISTS player_performances_match_id_d4093324_fk_matches_match_id CASCADE;",

                # Drop primary key constraint
                "ALTER TABLE matches DROP CONSTRAINT IF EXISTS matches_pkey CASCADE;",

                # Add new id column as primary key
                "ALTER TABLE matches ADD COLUMN IF NOT EXISTS id BIGSERIAL PRIMARY KEY;",

                # Add unique constraint on (match_id, ouid_id) - note: ouid is ForeignKey so column is ouid_id
                "ALTER TABLE matches ADD CONSTRAINT matches_match_id_ouid_unique UNIQUE (match_id, ouid_id);",

                # Add index on match_id
                "CREATE INDEX IF NOT EXISTS matches_match_i_feaf87_idx ON matches (match_id);",

                # Re-add foreign key constraints (using id instead of match_id)
                "ALTER TABLE shot_details ADD CONSTRAINT shot_details_match_id_fk FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;",
                "ALTER TABLE player_performances ADD CONSTRAINT player_performances_match_id_fk FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;",
            ],
            reverse_sql=[
                # Reverse migration (optional, for rollback)
                "ALTER TABLE shot_details DROP CONSTRAINT IF EXISTS shot_details_match_id_fk;",
                "ALTER TABLE player_performances DROP CONSTRAINT IF EXISTS player_performances_match_id_fk;",
                "ALTER TABLE matches DROP CONSTRAINT IF EXISTS matches_match_id_ouid_unique;",
                "ALTER TABLE matches DROP COLUMN IF EXISTS id;",
                "ALTER TABLE matches ADD PRIMARY KEY (match_id);",
            ]
        ),
    ]
