# Generated by Django 5.2.11 on 2026-02-15 00:14

from django.db import migrations


def forwards(apps, schema_editor):
    """Only run raw SQL if the old schema (match_id as PK) exists."""
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        # Check if matches table has match_id as primary key (old schema)
        cursor.execute("""
            SELECT column_name, data_type
            FROM information_schema.columns
            WHERE table_name = 'matches' AND column_name = 'id'
        """)
        row = cursor.fetchone()

        # If 'id' column already exists, the new schema is in place — skip
        if row is not None:
            return

        # Old schema detected: match_id was the PK, need to migrate
        statements = [
            "ALTER TABLE shot_details DROP CONSTRAINT IF EXISTS shot_details_match_id_4b0af562_fk_matches_match_id CASCADE;",
            "ALTER TABLE player_performances DROP CONSTRAINT IF EXISTS player_performances_match_id_d4093324_fk_matches_match_id CASCADE;",
            "ALTER TABLE matches DROP CONSTRAINT IF EXISTS matches_pkey CASCADE;",
            "ALTER TABLE matches ADD COLUMN IF NOT EXISTS id BIGSERIAL PRIMARY KEY;",
            "ALTER TABLE matches ADD CONSTRAINT matches_match_id_ouid_unique UNIQUE (match_id, ouid_id);",
            "CREATE INDEX IF NOT EXISTS matches_match_i_feaf87_idx ON matches (match_id);",
            # Update FKs to point to new bigint id
            "ALTER TABLE shot_details ALTER COLUMN match_id TYPE bigint USING match_id::bigint;",
            "ALTER TABLE shot_details ADD CONSTRAINT shot_details_match_id_fk FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;",
            "ALTER TABLE player_performances ALTER COLUMN match_id TYPE bigint USING match_id::bigint;",
            "ALTER TABLE player_performances ADD CONSTRAINT player_performances_match_id_fk FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;",
        ]
        for sql in statements:
            cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_playerperformance_user_ouid'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
