# Generated by Django 5.2.11 on 2026-02-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_match_id_alter_match_match_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotdetail',
            name='shooter_spid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
