# Generated by Django 5.2.11 on 2026-02-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_match_id_shotdetail_shooter_spid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotdetail',
            name='assist_spid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
