# Generated by Django 5.2.11 on 2026-02-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_assist_spid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shotdetail',
            name='hit_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shotdetail',
            name='in_penalty',
            field=models.BooleanField(default=False),
        ),
    ]
