# Generated by Django 5.2.11 on 2026-02-19

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Make Match.pass_success_rate nullable so that matches where no passes
    were attempted (passTry == 0) can be stored as NULL instead of 0.

    Note: The id column, unique_together, and match_id index were already
    applied via raw SQL in migration 0009.  We use SeparateDatabaseAndState
    to update Django's migration state without re-running those operations.
    """

    dependencies = [
        ('api', '0012_add_shot_type_fields'),
    ]

    operations = [
        # Record the state changes from 0009 (RunSQL) so Django's internal
        # state matches what is actually in the database.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='match',
                    name='id',
                    field=models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID',
                    ),
                ),
                migrations.AlterField(
                    model_name='match',
                    name='match_id',
                    field=models.CharField(max_length=255),
                ),
                migrations.AlterUniqueTogether(
                    name='match',
                    unique_together={('match_id', 'ouid')},
                ),
                migrations.AddIndex(
                    model_name='match',
                    index=models.Index(
                        fields=['match_id'],
                        name='matches_match_i_feaf87_idx',
                    ),
                ),
            ],
            database_operations=[],  # Already done via RunSQL in 0009
        ),
        # The actual change: make pass_success_rate nullable
        migrations.AlterField(
            model_name='match',
            name='pass_success_rate',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True,
            ),
        ),
    ]
