# Generated by Django 5.2.11 on 2026-02-28 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_player_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'site_visits',
            },
        ),
        migrations.RenameIndex(
            model_name='playerperformance',
            new_name='player_perf_match_i_2bf4dd_idx',
            old_name='player_perf_match_user_idx',
        ),
        migrations.RenameIndex(
            model_name='playerperformance',
            new_name='player_perf_user_ou_7a5d8d_idx',
            old_name='player_perf_user_spid_idx',
        ),
    ]
